name: CI on Push and Pull Request

on: [push, pull_request]

jobs:     
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd src
        nuget restore
        cd Xamarin.Netflix/Xamarin.Netflix.Android
        msbuild Xamarin.Netflix.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        cd src
        nuget restore
        msbuild Xamarin.Netflix/Xamarin.Netflix.iOS/Xamarin.Netflix.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
